repos:
  - repo: local
    hooks:
      - id: run-migrate
        name: Run migrate.py
        entry: bash -c "python migrate.py && git add ."
        always_run: true
        language: system
        types: [python]
